name: fundamentalis-combat
version: '1.0-SNAPSHOT'
main: me.tyalternative.fundamentalis.combat.FundamentalisCombatPlugin
api-version: '1.21'
authors: [TyAlternative]
description: A fundamentalis plugin
