name: fundamentalis-api
version: '${project.version}'
main: me.tyalternative.fundamentalis.api.FundamentalisAPIPlugin
api-version: '1.21'
description: "Moteur RPG Fundamentalis - API"
authors: [ TyAlternative ]